set -e
true
true
/Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/bin/spades-hammer /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/corrected/configs/config.info
/usr/local/bin/python3 /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/corrected/corrected.yaml --ext_python_modules_home /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/share/spades --max_threads 16 --output_dir /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/corrected --gzip_output
true
true
/Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/bin/spades-core /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K21/configs/config.info
/Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/bin/spades-core /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K33/configs/config.info
/Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/bin/spades-core /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/configs/config.info
/usr/local/bin/python3 /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/copy_files.py /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/before_rr.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/before_rr.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/assembly_graph_after_simplification.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/assembly_graph_after_simplification.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/final_contigs.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/contigs.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/first_pe_contigs.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/first_pe_contigs.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/strain_graph.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/strain_graph.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/scaffolds.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/scaffolds.fasta /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/scaffolds.paths /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/scaffolds.paths /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/assembly_graph_with_scaffolds.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/assembly_graph_with_scaffolds.gfa /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/assembly_graph.fastg /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/assembly_graph.fastg /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/K55/final_contigs.paths /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/contigs.paths
true
/usr/local/bin/python3 /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/SPAdes-3.15.5-Darwin/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/scaffolds.fasta --misc_dir /Users/janardhankarravula/Developer/masters/sem3-BINFO/finalProject/spades_output/misc --threshold_for_breaking_scaffolds 3
true
